#+TITLE: Rencontre avec Mathieu ce soir

* Rencontre avec Mathieu ce soir
** A propos du livre
*** Page couverture:

 Un belle photo de la maison avec comme texte: 220 1ère rue Mont-Suisse, Saint-Sauveur

 On aimerait une photo de drône.

*** Premières pages du livre
We discussed putting them not necessarily all together.

If you think it's nicer to put them in the middle.

**** Page 1

 Texte: "220 et 230 1ère rue du Mont-Suisse, Saint-Sauveur Québec."

**** Pages 2 et 3 ensemble
***** Pages 2

Titre: Un peu d'histoire sur un secret bien gardé depuis 50 ans
 
 Texte: Le domaine est construit sur un site historique qui offre une vue exceptionnelle
 sur le pittoresque village de Saint-Sauveur et les trois montagnes Mont Olympia,
 Mont Saint-Sauveur et Mont Habitant toutes illuminées les soirs d'hiver. C'est
 le gouvernement du Québec qui a fait dynamiter le haut du Mont-Suisse pour
 assoir la résidence qui devait servir à recevoir les dignitaires de différents
 pays en visite pour Expo 67 à Montréal. C'est une adresse qui rappelle que c'est
 la première rue construite sur le Mont-Suisse à la demande du premier ministre
 Johnson afin d'accéder au domaine.
 
 Depuis, la résidence a été réinventée. Transformations et rénovations ont depuis
 revampé le modèle initial en résidence moderne, épurée avec piscine à l'infini
 et jardins luxuriants. La maison qui servait à loger le personnel de service a
 été convertie en maison d'invités chaleureuse et accueillante.

***** Page 3

 220 et 230 1ère rue du Mont-Suisse c'est avant tout un art et plaisir de vivre.

 Dès qu'on franchit les barrières on se sent tout de suite en vacances. On est
 transporté dans un monde propice à la relaxation, loin de tout, mais situé à 40
 minutes de Montréal.
 
**** Pages 4 et 5

***** page 4

 Titre: Relaxation (Relax)

 Photos: La photo qui est à la page 14 du livre (avec les chaises léopard qui
 regardent un couché de soleil.

***** Page 5

 Titre : Évasion (Escape)

 Photos: [2018-09-05 19:39] I sent you an email with 8 pictures. You want
 =DSC_0996.jpg= from that series.  It's a fall landscape.


**** Page 6 et 7

***** Page 6

 Titre: Plaisir d'été (summer play)

 Photo: on [2018-09-05 19:42] I sent anothre e-mail with two pictures.  You want
 *EvasionReverie.jpg* from that other wetransfer transfer.  It's a pool scene.

***** Page 7

 Titre : Plaisir d'hiver (winter play)

 Photo: in the series of 6 pictures sent on [2018-09-05 19:44] you want
 =DSC_7362.jpg=. A picture of mont Habitant ski resort.

**** Page 8 et 9

***** Page 8

 Titre: Rêverie (dream)

 Photos: The large photo from [[https://studiolaflamme.smugmug.com/Suzanne-Gagnon-Photo-Album-One/n-KCNB7V/i-ns5dMPZ/A][This page in the book]] 

***** Page 9

 Titre: Luxe Calme et Volupté (/Find English/)

 Photos: The large photo from [[https://studiolaflamme.smugmug.com/Suzanne-Gagnon-Photo-Album-One/n-KCNB7V/i-xZQSRfP/A][This page in the book]]. Living room with sunshine.


*** Série de photos
 Voir draft [[https://studiolaflamme.smugmug.com/Suzanne-Gagnon-Photo-Album-One/n-KCNB7V/i-xZQSRfP/A][Album en ligne]] on pourra choisir des photos ensemble en fin de
 semaine.
*** Pages descriptives

 Placer après la série de photos.

***** Page Description sommaire

 Titre: Description Sommaire

 Texte: À 40 minutes de Montréal
 À 5 minutes de restaurants gourmets , de commerces variés tel épiceries fines, traiteurs etc 
 À proximité de 6 centres de ski: Mont  Avila, Mont Saint-Sauveur, Mont Habitant, Mont Olympia, Mont Gabriel, Morin Heights 
 
 
 Grande cuisine
 Salle à dîner
 3 salons: 1 avec foyer au bois avec devanture en marbre, un salon un avec foyer au gaz et un salon pour regarder la TV
 Un emplacement à part pour table de pool
 4 chambres à coucher distribuées sur 3 étages pour offrir une plus grande intimité. Toutes avec salle de bain attenante.
 2 salles de bain genre powder room
 3 thermopompes 
 Piscine à l'infini
 Jardins luxuriants
 Maison d'invités avec cuisine, salon, foyer, 2 chambres à coucher et une salle de bain avec douche.
 
 Deux garages pouvant accommoder 4 limousines, un situé sous les appartements de la maison d'invités. Un autre dans un bâtiment à part qui contient aussi un grand espace pour rangements divers.



*** Insérer les pages suivantes du rapport Meloche et Associés
 Voir le Rapport de Meloche et Associés que je t'ai envoyé [2018-09-05 20:08].
  - Page couverture.
  - Page 3 : Sommaire du rapport : Immeuble à l'étude
  - Page 6 : Généralités
  - Page 7 : Description du bâtiment
  - Page 8 : Aménagement intérieur


** A propos de la photo en 3d pour site web

** A propos de photos avec drone pour site web
