#+TITLE: Transcription de l'entrevue

* GY

... Je les utilise pour faire des choses

... Là j'ai pas de TBI (regard triste)

JULES : Je sais qu'il y a moyen d'avoir les manuels, les cahiers sur le TBI,
etes vous prise sans [cahiers physiques maintenant que le TBI ne fonctionne
pas].


Je suis sans cet outil là depuis presqu'un mois puisque [la lampe doit être
remplacée] alors je l'utilise pas depuis un mois.

JULES : Est-ce que vous avez fait le choix pour la classe de ne pas avoir les
cahiers papier?

GY : Non, ils ont aussi les cahiers papier. [Pour] Tous les 4e années, on
a vraiment tous les manuels.  On a les corrigés sur le TBI, on a les manuels
aussi sur le TBI. On peut travailler sur le TBI, faire les exercices dessus. 

Mais on a les copies papier que chaque enfant ont.

JULES : Donc si je comprends bien, un prof n'est pas totalement pris au
dépourvu, sans alternative au matériel sur TBI.

GY : On n'est pas /totalement/ dépendants.  Cependant on se rend compte
que quand on est habitué avec un TBI et par exemple on veut faire de la
géométrie, on veut faire des plans cartésiens, avec le tableau et une craie
c'est pas si évident.  Tandis que le TBI, ben tsé tu clique, ton tableau
apparaît, tu lui donnes le nombre de cases que tu veux.  C'est plutôt facile.

Mais bon, on se débrouille.

** Début du questionnaire

PHIL : Vous enseignez la 4e année (elle nous l'a dit quand on s'est présentés).
Combien d'élèves y a-t-il dans votre classe?

GY : 19

PHIL : Depuis combient de temps vous enseignez la 4e année

GY : Depuis janvier cette annéee.

PHIL : Depuis combien d'années enseignez vous au primaire?

GY : 5 ans au primaire

PHIL : Depusi combien d'années avez-vous un TBI dans votre classe?

GY : J'en avais jamais eu avant puisque moi c'est un retour à l'enseignement.
J'en avais pas à l'époque mais je l'ai depuis que je suis arrivée ici en
janvier.

PHIL : Comment décririez vous votre niveau d'expertise avec le TBI?

GY : Ben moi j'aimerais l'utiliser plus à fond. Parce que je le connais par ce
que j'ai expérimenté moi-même.  Cependant j'aimerais avoir une formation pour
être capable de l'exploiter plus à fond.  Parce que je sais qu'on peut faire
pleins de trucs avec le TBI.  Faudrait qu'on ait le temps peut-être de
travailler avec le TBI mais idéalement d'avoir une formation.

Pour pouvoir exploiter n'importe quel outil technologique adéquatement et à
fond, faut savoir comment ça fonctionne.

Y'a pas de manuel d'instructions.  C'est sur tu peux toujours aller voir ... je
suis allée voir des tutoriels sur YouTube mais ... encore là, quand on arrive
sur le plan paratique et qu'on te montre comment ça fonctionne, tu peux faire ça
tu peux faire ça tu peux faire ça ((elle parle d'une formation en personne)), tu
peux poser des questions, tu peux l'essayer en même temps.  Ça serait l'idéal.

JULES : Juste pour revenir, je suis pas sur, vous avez 5 ans d'expérience.

GY : En enseignement oui, peut-être un peu plus, j'ai enseigné au CEGEP aussi.

JULES : Et vous êtes revenue à l'enseignement primaire cette année.

GY : Oui.  Et c'est la première fois que j'utilise un TBI.  Au CEGEP on n'en
avait pas.  On arrivait avec notre portable.  Ça n'avait rien à voir avec les
TBI.  On apporte nos portables et on se branche au projecteur.

Donc pour travailler avec un TBI, pour moi, c'est nouveau depuis janvier de
cette année.  C'est pas parce que c'est arrivé ici en janvier, c'est moi qui
suis arrivée en janviern.

JULES : OK

PHIL : Avez vous fait un bacc en éducation préscolaire et enseignement primaire

GY : Exact. 

PHIL : Avez vous étée formée à l'utilisation des TBI à l'Université?

GY : NON

PHIL : L'avez vous utilisé durant vos stages?

GY : Non, à l'époque il n'y en avait pas.

PHIL : Avez vous étée formée à l'usage du TBI une fois sur le marché du travailˆ
GY : Ben sur le marché du travail, quand j'ai étée confrontée aux TBIs, c'était
en janvier quand je suis arrivée ici.  

Est-ce que j'ai étée formée aux TBI, non pas du tout.  On m'a dit "T'as un TBI"
puis là ben "t'as un ordi" pis là ben "tu peux te brancher".

J'ai dis c'est bon, je suis autodidacte puis j'ai ... pas nécéssairement une
facilité avec les technologies puisque je trouve que c'est parfois irritant les
technologies quand ça brise ((comprendre ici "quand ça fait pas ce que je
veux")) c'est autre chose.  Mais euh j'suis habituée avec les ordis... les
logiciels et tout.  Je l'ai appris rapidement.

Mais maintenant, est-ce que je l'utilise à fond?  Vraiment pas.  Ça c'est clair
que non. 

PHIL : Quelle est votre fréquence d'utilisation du TBI

GY : Ben quand je ... Tout le temps.  En fait presque tout le temps.  Parce que
... qu'importe la matière que tu donnes, que ce soit /français/ on travaille
avec /smart.../ ((un logiciel qui s'appelle 'smart qqch')) on fait des phrases,
[on travaille] la composition des phrases.

Que ce soit en mathématiques on travaille toujours avec le TBI.  Même si on fait
des travaux qui sont, par exemple [en] histoire/géographie, on veut montrer ce
que ça va donner au final.  On fait un cahier interactif et on peut montrer
/voici ce que ça peut donner au final/.  On le montre sur le TBI.

Autrement, moi j'avais pas mon TBI parce qu'il était brisé, alors je débranche
mon ordi et je me promène avec mon ordi portable dans la classe.

Mais tsé, moi,... c'est un outil qui est majeur.

TU peux difficilement... en tout cas, je retomberais pas avec les craies et le
tableau comme j'ai fait depuis le dernier mois.

On trouve ça difficile pis je dis /on/ parce que c'est pas juste moi, les
enfants aussi trouvent ça très difficile de pas avoir accès aux TBI.  Pour
toutes sortes de raisons. 

Parce que quand  on fait des ateliers d'écriture, habituellement, je mets de la
musique classique... ben on passe par le TBI pour mettre la musique classique
pour faciliter la concentration.  [Sans le TBI], je prends mon iphone et je met
de la musique.

J'essaye de trouver des moyens pour pallier mais ... non, sans TBI c'est ... ça
deviendrait difficile. 

JULES: Est-ce que ce sont des élèves qui ont eu un TBI depuis le début [de leur
arrivée à l'école]?

GY : Je pense que oui. 

PHIL : ((Se sentant un peu niaiseux de poser cette question)) Quels sont les
raisons qui vous retiennent de l'utiliser d'avantage.

GY : Je pourrais surement l'utiliser d'avantage si j'avais,... parce que je suis
a peu près certaine que je l'expoite pas à font.  Si j'avais une formation, je
pourrais peut-être l'exploiter mieux et peut-être travailler plus avec le TBI.

Mais tsé je pense que aussi, tsé au niveau de nos outils on a des exercices qui
sont faits pour le TBI, donc on peut travailler avec ça.  Y'a comme pas de
raison pour qu'on puisse pas l'utiliser.

Tu vas sur les sites [comme] allo-prof, la plupart des jeux interactifs se font
au TBI donc .. je sais pas /jogging mathématique/ avec le lapin qui cours tu
touches au TBI pour donner ta réponse.

Alors c'est pas juste pour montrer des choses, c'est pas juste pour écrire, 
ça peut être aussi pour jouer sur un plan éducatif. 

Alors oui, je pourrais probablement l'utiliser plus mais j'en fais quand même
une utilisation du matin jusqu'au soir.

PHIL : En ordre d'importance, pour quelles raisons utilisez vous le TBI?  Par
exemple, projeter des choses à l'écran, faire des recherches sur Internent,
faire des démonstrations interactives, ou autre?

GY : Moi l'utilisation que j'en fais, c'est d'abord pour faire des exercices. Les
élèves viennent au TBI comme ils viendraient au tableau 

Parce que je pesne que c'est important de voir ce qu'un enfant comprend et ce
qu'il ne comprend pas.  Et comment il arrive à la bonne ou a la maivaise
réponse.

Parce que dire "oui, la réponse c'est 4500"... oui mais encore?  C'est comme
résoudre le problème, et de dire "j'ai la bonne réponse" mais t'as pas la démarche.  La démarche
est importante.  Alors on amène les enfants au tableau.

Je pense donc que la première importance, c'est le travail au quotidien.  D'être
capable de ... d'amener les enfants au tableau pis voir quels sont leurs
raisonnements pour donner les réponses, pour arriver aux bonnes ou aux mauvaises
réponses.

((On peut retenir ici *amener les enfants au tableau* comme la chose qu'elle
croit être la plus importante))

Ensuite, pour la projection... quand on travaille de façon interatcive ou encore
tout simplement pour le jeu en apprenant.

PHIL : Avez vous remarqué une différence dans le niveau d'attention des élèves
depuis l'implantation du TBI.

GY : C'est difficile pour moi de répondre à cette question là puisque quand je
suis arrivée, les TBI étaient déjà implantés.  Le TBI était déjà là, c'est /moi/
qui me suis implantée ((LOL)).

JULES : Mais vous avez enseigné au primaire dans un temps où il n'y avait pas de
TBI.

GY : C'était il y a longtemps, j'ôserais pas me prononcer là dessus parce que
c'est un retour après plusieurs années.  Je suis pas une jeunesse.  J'ai quand
même mon âge, 52 ans.  Donc euh tsé, il y a longtemps j'ai enseigné sans TBI au
primaire ensuite je suis passée au CEGEP, y'a pas ce genre de truc là ((pas de
TBI au CEGEP)).

Maintenant j'arrive ici, le TBI est déjà là alors est-ce que je suis capable de
faire un parallèle entre l'un et l'autre.

Je peux faire un parallèle maintenant en disant j'avais mon TBI et je ne l'ai
plus depuis un mois. Oui ça l'a un impact. Ça a un impact négatif ((le manque de
TBI)), c'est-à-dire que souvent les enfants vont dire "Oui mais qu'est-ce que ça
donne au final, ça qu'est-ce que ça veut dire?". On leur montre à chercher sur
le dictionnaire. Puis on cherche aussi sur internet.

On le fait sur le vrai dictionnaire, parce que c'est important qu'ils
connaissent l'outil physique, mais qu'ils passent par internet aussi.  Avant
((avec TBI)) un enfant pouvait venir [au TBI] faire sa recherche, les autres
lisaient la définition en groupe.  On pouvait mettre en commun les choses plus
facilement ((*facilite son travail*)). 

Maintenant, on ne l'a plus, ça devient plus difficile.  Mais je peux faire un
comparatif là.

PHIL : Avez vous remarqué une différence dans le niveau de motivation des
élèves depuis l'implantation du TBI.

Et bien, la motivation, c'est sur qu'il y a une plus grande motivation quand on
travaille avec les équipements.  Quand on travaille avec des équipements comme
le TBI, les enfants sont plus /portés/ à être attentifs ((*facilite son
travail?*)) que si on y vas avec un tableau et une craie, ou une feuille et un
crayon.

Oui, par rapport à l'attention comme tel, c'est plus /vivant/, c'est plus
interactif, les enfants participent et ils ont l'impression d'être beaucoup plus
solicités alors oui ils sont plus présents. ((affecte positivement le niveau d'attention des élèves)).


PHIL : Pouvez vous dire aussi comment les TBI impactent le niveau d'interactivité
des cours

GY : À un niveau assez élevé oui, puisque la plupart de nos travaux, quand on a
le TBI on peut les faire, les compléter, les expliquer, à partir du TBI. Alors
oui, ça a un impact direct sur ... même j'te dirais sur l'apprentissage des
enfants puisque c'est visuel, les enfants peuvent venir le faire, alors ils
peuvent, quand on fait des exercices ils peuvent /toucher/ le TBI pour être
capables de déplacer des formes comme en géométrie ou quoique ce soit.  Ça a un
impact très grand sur l'apprentissage des enfants.  C'est clair.

PHIL : Pouvez vous commenter sur comment ça impacte le nombre de fois par jour
que les élèves viendraient au tableau.

Avez vous remarqué une différence dans le nombre de fois que les élèves se
rendent au tableau avec ou sans TBI.

GY : Avec le TBI, je dirais qu'ils viennent plus souvent au tableau.  C'est plus
facile [de les faire venir au tableau].  Ne serait-ce qu'au niveau de la
rapidité, c'est facile, c'est rapide effacer un écran.

Quand t'arrives au tableau à craie (parce que je le vis depuis un mois) on
cherche la brosse, la brosse est pas là ils deviennent pleins de poussière, ils
échappent la craie tombe ... *Je trouve que c'est pas efficace*, je trouve ça
aussi un peu salaud perso pour moi. *Et les enfants, je suis moins portée à les
envoyer au tableau vert qu'au TBI.*  Au TBI, *c'est plus rapide, c'est plus
facile*, *c'est plus clean*, c'est plus propre.

Perso là quand il s'agit de faire des exercices au TBI, c'est "vient-en au TBI"
et les enfants /aiment ça/. Au tableau aussi ils aiment ((avec intonnation pour
dire quelque chose comme "à peine", c'pas comme si ils aimaient pas venir au
tableau vert mais...)) ça mais je m'en sers moin alors les enfants vont moins au
tableauv ert qu'au TBI ((On peut oublier la dernière phrase et retenir que c'est
plus facile pour elle de faire venir les enfants au tableau, c'est pas mal ça
qu'elle dit si on oublie la dernière phrase.))

Mais c'est par rapport à moi, parce que je suis un peu irritée par le tableau
vert ((pas dans le sens allergie à la craie, mais on voit dans sa face que ce
qui l'irrite, c'est "j'ai un TBI, pourquoi j'me ferais chier à enseigner en
grattant une roche sur une autre roche)).

Si je n'avais pas la technologie du TBI peut-être que ça ne serais pas le cas.
Je dirais pas ça.  Le tableau vert fait la job.

Mais une fois que t'as connu la technologie du TBI, tu veux pas vraiment
retomber au tableau vert et à la craie.

PHIL : Avez vous remarqué une augmentation ou une diminution du nombre de
questions posées par les élèves, avec versus sans TBI.

GY : Je dirais que c'est relatif, ça dépend.  Quand on est dans des matières
traditionnelles je ne crois pas que ça change quelque chose.  Mais quand on
arrive par exemple en géographie ou en histoire, là où il y a des images, là où
il y a de la couleur, là où il y a de la vie.  Quand on regarde la carte du
Canada ou la map-monde, /là il y en a des question qui sont suscitées par
l'image, le visuel. Ça solicite les enfants/ ((C'est plus facile pour moi de
soliciter les enfants)).

Tandis que si je prends une carte, la carte du monde [physique], c'est pas
pareil, c'parce que le TBI c'est facile changer d'image, c'est rapide.  La carte
du monde [physique] j'ai été obligée de m'en servir /physiquement/ ((dit avec un
genre de mépris commique)), elle est /toute pliée/ et je la tenais dans mes
mains, j'ai essayé de la faire tenir sur le TBI avec des aimants n'étaient pas
assez forts.

Donc oui, le TBI va amener plus d'attention ((parce qu'on ne perd pas de temps à
se gosser sur des conneries)).

Et aussi au niveau visuel, je peut mettre plus de visuel dans mes cours.  Ça
attire plus les enfants que d'expliquer ou de travailler avec une craie blanche.

PHIL : Diriez vous que le TBI affecte votre niveau de créativité dans la
préparation des cours.

GY : Jusqu'à un certain point oui, moi ça me rend plus créative.  Pourquoi, ben
parce que j'ai accès à des vidéos, j'ai accès à internet, j'ai accès à du
matériel auquel je n'aurait pas accès autrement.  Si t'as pas de TBI, j'ai quand
même accès par mon portable, mais comme j'ai dit je mets mon portable sur une
petite table au centre de la classe et les enfants viennent s'agglutiner autour
de la table pour voir [une chose que je voudrais leur montrer].  Mais tsé, c'est
beaucoup plus simple si tu le fais au TBI.

Est-ce que je me sens plus créative?  Oui, c'est plus facile de rendre un cours
plus intéressant... puisque t'as des outils, même en maths le vendredi
après-midi, moi le coloriage [sans TBI] oublie ça, mais [avec TBI] on peut aller
sur le site allo-prof, on peut aller sur net-math, qui sont des sites internet
extraordinaires que les enfants apprennent.  Pis on fait des exercices
directement sur le TBI et les enfants /aiment/ ça.  On fait des combats et tout
ça.

Alors oui, c'est sur que ça a un impact direct sur la .. sur ce que tu donnes
comme enseignement et par conséquent sur ta créativité.

PHIL : Est-ce que l'arrivée des TBI a influencé votre niveau de satisfaction
personnelle par rapport à votre enseignement?

GY : Au niveau de satisfaction personnelle?  ((Réflexion))  Ben c'est plus
facile.

Oui, je dirais que oui, parce que l'enseignement me paraît ... en tout cas ...
y'a ... c'est pas /l'acte/ d'enseigner qui est plus facile, mais je pense que
l'organisation, ce dont on a besoin pour préparer nos cours, ça donne une
certaine facilité.

JULES : Donc au niveau de votre performance, l'efficacité de la transmission de
savoir avec le TBI, versus pas de TBI, vous dites que ça marche mieux, vous êtes
plus satisfaite de votre travail? 

GY : Tout-à-fait, oui.

PHIL : Avant l'installation du TBI, à quelle fréquence rencontriez vous des
problèmes techniques?

GY : Des problèmes techniques avant l'installation des TBI? Du genre ???

PHIL : Comme la photocopieuse qui ne marche pas... c'est dur pour un tableau de
ne pas marcher.

GY : Oui c'est ça, peut-être le photocopieur.  C'est sur qu'il y a toujours des
irritants.

JULES : Et maintenant qu'il y a des TBIs, quelle est la quantité ou la fréquence
des problèmes.

GY : Un peu plus, un peu plus.  C'est normal puisque c'est associé directement à
une technologie.  Alors c'est sur que y'en a.  T'implantes une technologie, ben
tu prends tout ce qui va avec.   Parfois ce qui va bien, parfois ce qui va moins
bien. 

Tsé y'arrive des trucs des fois, comme *les changements de version ou de
logiciels*.  Il y en a eu une récemment qui a faite que je n'avais plus accès à
tout ce que je faisais sur SMART.  Je pouvais plus l'envoyer au photocopieur.
Ça se rendait pas.

On a un technicien qui est ici un jour et demi par semaine.  Faut que ça brise
pendant la journée et demie qu'il est là.  Parce qu'autrement t'attends trois
jours et demie avant d'avoir ta solution.

Donc c'est sur que ça a un impact, les problèmes augmentent un peu.

Comparé au service que ça rend, c'est pas un irritant comme tel.  Ça fait partie
de la vie, les technologies.

(( L'impression que j'avais, c'est qu'elle voyait ça comme si le TBI augmentait
pas le nombre de problèmes techniques dans le sens ou jamais avoir de TBI serait
un plus gros problème technique que de l'avoir mais pas 100% du temps parce
qu'il brise.))


PHIL :  Quelle est la fréquence à laquelle il vous arrive de ne pas finir un
cours à temps.

GY : C'est difficile à dire.  Puisque j'arrive à l'enseignement au primaire avec
le TBI.  Donc difficile de faire un comparatif pour ma part.

JULES : Et depuis qu'il a brisé, est-ce que vous finissez plus à temps ou moins.

GY : Ça m'enlève de l'efficacité, le fait de ne pas avoir le TBI.  Puisqu'il y a
des choses que je ne peux pas faire.  J'le disais tantôt.  Y'a des trucs que je
ne peux pas faire des vois.

Je suis obligée de me promener avec mon portable et les faire regarder ce que je
veux leur montrer.  Ça alourdit un peu.  Ne serait-ce que faire des exercices au
tableau, /c'est long!/  C'est long parce que là l'élève arrive, y'a pas de
craie, la craie est tombée, la craie est cassée, y'a rien que des petis morceaux
..., pis là y'a plein de poussière de craie pis c'est c'est long, pis là ils
prennent la brosse pis là y'effacent pis ça fait plein de poussière.  Et ils
font des coeurs dans la poussière de craie.

Des fois c'est n'importe quoi, mais reste que /c'est moins efficace/ de pas
avoir [ces problèmes].  Tsé, je trouve que le tableau, mais en efficace, en
clean, en branché, en propre, alors c'est comme le nec plus ultra du tableau à
craie.   Et pour tout aussi, la *géométrie*, on peut faire des formes, on peut
les déplacer, on peut faire des angles, tsé c'est toujours droit.

J'essayais de montrer l'aire et le périmètre cette semaine, sur le tableau à
craie.  J'ai pas de facilité moi à tracer des lignes droites.  Moi c'est
compliqué faire des lignes droites.  Ça va toujours soit en montant, soit en
descendant.  Mais c'est jamais droit.

Mes carrés ressemblaient à des... chépas, y'avaient tous des mauvais angles.

Et les élèves devaient me demander si les formes que je dessinait représentaient
bien un carré et je devais leur dire "oui, oui, c'est un carré".

Mais avec le TBI, tu te poses pas la question.  Tu veux ton carré, le vla, tu
fais ton cercle, le vla!  Tsé t'as ton compas, tu peux faire ton rayon.

PHIL : Comment décririez vous l'impact du TBI sur la durée de l'enseignement?
Donc est-ce qu'un même cours se donne plus rapidement avec ou sans TBI.

GY : [skip la question]

PHIL : Question charge de travail.  Comment diriez vous que l'implantation du TBI
impacte la durée de préparation des cours.  Est-ce que ça prend plus de temps à
préparer un cours ou moins de temps.

GY : Ah ça prend beaucoup moins de temps.  Par exemple, ne serait-ce que le lundi
matin on fait le plan de travail.  À savoir quels sont les devoirs et leçons
qu'ils devront faire.

Le fait de ne pas avoir de TBI, m'oblige à le faire [en document informatique].
Habituellement, le lundi, les enfants arrivent et c'est affiché au TBI et ils le
retranscrivent dans leur agenda.  Là je suis obligée de l'/imprimer/ ((dit avec
une dédain comme si c'était un acte primitif)) 19 fois.  Et de les distribuer.

Et c'est des feuilles 8.5x11 et l'agenda a des dimensions différentes (8x10).
Donc la feuille ne rentre pas.  Ils sont obligés de la couper, mais ils ne
peuvent pas couper tout du même bort, ils doivent coupper un peu de chaque bord
pour ne pas enlever le texte.  Ils sortent le tub de colle ... /ça fini pu/!

Autrement je fais quoi, /je le retranscris au tableau vert... à la craie/ ((avec
léger dédain)).  Et je leur dis retranscrivez le à nouveau dans votre agenda.
Tsé à moment donné, on peut tu être efficaces?  Alors ((lève les bras)) prends
une photocopie et coupe la.

PHIL : Est-ce que ça vous arrive de préparer deux versions du même cours, une
pour TBI et une sans TBI au cas où le TBI ne marcherait pas?

GY : Non.  Je me suis fait prendre.

PHIL : Avant l'installation des TBI, combien d'heurs de formation suiviez-vous
par année.  Versus aprés.

GY : Ne s'applique pas.

PHIL : Est-ce que les formations relatives à l'usage des TBIs nécéssitent le
développement de nouvelles compétences.

GY : Est-ce que ça nécéssite le développement de nouvelles compétences?  Chez
l'enseignant?

PHIL : Oui

GY : Ben euh, un minimum genre.  Un minimum.

JULES : Mais vous avez pas eu de formation

GY : Je n'ai pas eu de formations.  Mais est-ce que ça demande des nouvelles
compétences pour l'enseignant?  /Il y a un minimum de compétences que ça exige/.
Est-ce que j'ai eu une formation, non.   J'avais entendu parler des TBI, je
savais pas comment ça fonctionnait puisque ça ne faisait pas partie de ma vie,
j'étais en affaires.  C'est pas quelque chose qui faisait partie de mon
quotidien mais je l'ai vu et appris comment ça fonctionnait très rapidement.

Mais bon, est-ce que c'est complexe?  Absoluement pas.  Maintenant est-ce que je
pourrais avoir de la formation pour l'utiliser optimalement, surement.

PHIL : Est-ce que l'implantation des TBI ont eu un impact sur votre charge de
travail totale?

GY : NON.

RELATIONS DE TRAVAIL

PHIL : Diriez vous que votre utilisation du TBI est motivée principalement par
des raisons internes (comme votre préférence) ou par des raisons externes comme
les directives de la direction, commission scolaire, parents.

GY : Oh ben je dirais, on utilise les TBIs, mais en même temsp c'est pas vraiment
un choix personnel.  Moi je l'utilise et ça serait personnellement mon choix.

Je l'ai expliqué et j'ai élaboré longuement là dessus.  Mais est-ce que c'est un
choix personnel d'utiliser le TBI.  Par exemple [si] t'es contre les
technologies, ou tu aimes ton tableau à craie, tu voudrais le garder ... ça n'a
pas sa place ... au niveau de la direction de l'école.

Puisque moi, arrivant dans le milieu, je suis évaluée et l'utilisation des
technologies est /très/ importante dans l'évaluation.  Si comme nouvelle
enseignant tu n'utilises pas optimalement les technologies qui te sont
présentées, c'est noté à ton dossier.  Faut se rendre compte qu'on forme des
enfants de l'avenir donc il faut que /nous mêmes/ on puisse utiliser ces
technologies là pour être capable de les transmettre aux enfants.

PHIL : Pouvez-vous décrire l'impact des TBIs sur vos relations avec vos
collègues, vos élèves ou la direction?

GY : ((Incrédule)) L'impact des TBIs sur mes relations?  Avec mes collègues.

Ça a un niveau de facilité, quand on se rencontre, ben on fait, par exemple pour
faire les examens, on les fait direct sur le TBI [avec tout le monde dans la
classe].  Même si on est un petit groupe, 3-4, on pourrait difficilement être
3-4 autour d'un portable.

Tandis que là on a l'impression de le faire /live/. Et on est tous ... ensemble
par le TBI.  Le TBI vient nous lier sur le travail qu'on fait comme tel.

Alors oui, ça a un impact nos réunions, sur nos échanges entre nous puisque
c'est un *agent facilitateur*.  C'est clair.

SANTÉ AU TRAVAIL

PHIL : Diriez vous que l'implantation des TBIs a modifié le niveau de buit dans
la classe.

GY : Non.  Je fais un comparatif avec quand je l'ai pas et quand je l'ai.  Non,
pas de différence.

PHIL : Souffriez vous de fatique oculaire avant les TBIs,... et Après?

GY : Absoluemnt pas, [ pas avant, pas après ].

PHIL :  Votre vue a-t-elle changé après l'installation et l'utilisation des TBIs.

GY : Ma vue a récemment changée mais ça n'a rien à voir avec les TBIs, ça a tout
à voir avec mon age.

PHIL : Combien de journées de maladie avant versus après.

GY : Pas de différence.

PHIL : Quel est votre opinion sur les TBIs, pour ou contre, qu'est-ce qui est
bien, qu'est-ce que vous changeriez?

GY : Quoi dire de plus.  Je ne m'en passerais pas.  En fait demain la nouvelle
lampe sera installée et j'ai bien hâte.  Et les enfants aussi.  Ils s'en sont
fait une fête.  Ils sont comme "yay, on va avoir le TBI vendredi pm" je leur ai
dit "oubliez ça, ils viennent l'installer vendredi PM, on va l'avoir lundi".

Donc ça nous rend excités, c'est comme une joie.  C'est niaiseux, mais c'est
quand on est privé d'un outil qu'on juge important qu'on l'apprécie.
